### ISSUE TITLE
how to run example usage based on your data and code

### ISSUE THREAD

**Issue by weisongwen** [karoly-hars/MASAT_IG_for_SLAM#1]
Hi @karoly-hars, Thanks for sharing the your interesting work. I am curious about how to run example usage on your data and code?

Best，
Weisong，

**Comment by karoly-hars** [comment]
After compiling, run `./MASAT <PATH_TO_INPUT_FILE> <PATH_TO_OUTPUT_FILE>`. The input file has to be in .g2o format, the output file will be created by the script (also in .g2o format).
